name = "play-purchase-worker"
main = "index.js"
compatibility_date = "2025-08-26"  # HARUS HARI INI ATAU SEBELUMNYA

[vars]
GOOGLE_CLIENT_EMAIL = "iap-verifier-379@onesignal-6e467.iam.gserviceaccount.com"
GOOGLE_PRIVATE_KEY = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5Os8u0pkfqGyj
J2fa+59PZKThJVVsag/UNlWNf1psCMLgH8DgMiZ91nYrLSc9cw6KFt2Ynaf/I/I3
V0MU/DhCJUWuHwTiXwOlbQkcrcPVaEB4YwBNYvEUN9NBlboobsTYdWWIzUTwlnzI
qGgFdfel1UaZ5rf+NIl3nd24HXFyJyidFlA8O05QeRz/JqX/c9KKQ/AXX3UkkZXi
ahyqZgj4yeuG9pdz1Cm4ZsYK6TQ/HcH69jb5WfdlmnfDyusPph5mgz6485cBs4P4
ARDHtPpOpOFVNyJiVUlTUYLsIa4xSZQi5rSsHkSuVxQtWggaZBazrpl/YzJb/m/P
b7sJVgclAgMBAAECggEALeloB7LPHgP084bVrPdwADGR1bWXhCEQ7diO4Zz2uG7+
gKeWOuvrUwcYsLCHOKm/aZZr1EOFq83I4JM6TyYKOsj6ycMqBoMnB/asCsX+U7P8
wOpHHadf2pNQw4GdjB6Sn5WPtnYst5aRdPobGHlqShpAXu7LXdC/Xx0L4zI3F6Q1
rf6m0MxFbjSZGKiuVNO1R2nHolinu+UJMhXdSCsW1WCcl7UzpdtRHACRw5vtduUi
xQeM4pMcsqi3/m1IBT/JK5BRYlOL6IHJyUaMP/SH9j/m9Mrbi83XymzorsYYR2kx
HrYgda6t1ibjYMq02gbwzWsQ8LCdMONXnFggwFIaaQKBgQDb4Cji1LAnWItoc7Sl
x3v3Vb7g0j2xHBaEHDi7Exojw29FeiAXwdY5JjkKKiNxnn04O8MGGS79xRCOEyk8
KuGfS84YFqFNiOvkKw2GfWKAvGIpDVKzlHPYrlOHT3ba/H4VD9SIkpC2x8CdmcVt
nMf6utq/wlENgpWbxBOQomqujQKBgQDXqXaZsXQx7PKdDiA+vHL7o9vxzUfm/JsP
RDtb6MJKuywSd0vIX3TbX52cGq1vNzLsvLFv40K9bgHoGJGJ2cI7e6bisWN3CxNJ
2QKI7leA4hqb3xRO/cRy9foFh5eyOcFyAOqK4UceBPXi0jkNALk9QxWFtI1TTdbu
eFEg62tA+QKBgQC1nYmIG3BJf6zfITuk94pg+VWKNH66rV23z+vYMmYUBlkBxWd+
2CBP4k+ZIsdWETiTW2Gyxth2yvDquc8EoNLullnssbyY47EdLaalYSoc9f4KtLOM
G+I4p33dNXkSVx753LKMAKxCHervAtX9vVO9udv4KtRyWVukZyhV/qIp/QKBgB3h
JMV2iJrCMXsBEgafJW8n7Lk7r9KY/QLIeVDqlsCz3g9Q5/cDArXCMZwHNjBKfYu/
OPY/jmegbjMx9DgdK4QCRcTyvs0ng6yfnHJMU2NP8E/YQIAROL6UxecuOh4/UkXx
So2jWK8YENk0NyNODlwmhzzXHx2Dk1vG37an51xBAoGAB/6wK0W7VfR4kZSWJHZC
EPNs2DfBCfAhT5b3D0Kc534hMCz0vB5ZdX6N2MN5lfQuPMmqnH18fj4RYDtD61W9
ywn399Pj9VmQEyxiCMj+Muyk+UXGbLdqkckxNSwZDOJGD8QixWZFZCe8/TGFNl4O
i9LDNALabbBcL5oLw5fPMFc=
-----END PRIVATE KEY-----
"""
PACKAGE_NAME = "com.chatmoz.app"

[observability.logs]
enabled = true

